# Generated by Django 4.2 on 2023-04-16 20:48

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_writemodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='writemodel',
            name='content',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
