# Generated by Django 4.2 on 2023-04-16 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_commentmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommunicationModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=250)),
                ('name_surname', models.CharField(max_length=150)),
                ('message', models.TextField()),
                ('create_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Communication',
                'verbose_name_plural': 'Communications',
                'db_table': 'communication',
            },
        ),
    ]
